[build]
  command = "npm run build:production"
  publish = "public"

HUGO_VERSION = "0.40.3"

[context.production.environment]
  HUGO_VERSION = "0.40.3"

[context.deploy-preview]
  command = "npm run build:preview"
